"""Generate the measure dictionary, and check it against what was actually built.

Run:  python scripts/generate_measure_dictionary.py

config/metrics.yml is the single definition of every metric. This script does
two things with it:

  1. renders reports/measure_dictionary.md, so the human readable document
     cannot describe a metric differently from the file the warehouse is
     built from

  2. checks that every metric named in that file exists as a column in
     mart_agency_month, and that mart_agency_month has no measure column that
     the dictionary fails to define

The second part is the one that matters. A dictionary that is written by hand
drifts away from the mart within about two changes, and then it is worse than
having none, because it is confidently wrong. This exits non zero on drift, so
the Makefile stops.
"""

from __future__ import annotations

import sys
from pathlib import Path

import duckdb
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config import load_config  # noqa: E402

# Columns in the mart that are dimensions or supporting counts rather than
# metrics in their own right, so the dictionary is not expected to define them.
NON_METRIC_COLUMNS = {
    "cohort_month",
    "agency_key",
    "complaint_type_key",
    "complaint_type",
    "borough",
    "is_cohort_mature",
    "on_time_denominator",
}


def load_metrics(repo_root: Path) -> dict:
    with open(repo_root / "config" / "metrics.yml") as fh:
        return yaml.safe_load(fh)


def render(spec: dict, cfg) -> str:
    lines: list[str] = []
    lines.append("# Measure dictionary")
    lines.append("")
    lines.append(
        "Generated from `config/metrics.yml` by "
        "`scripts/generate_measure_dictionary.py`. Do not edit this file by "
        "hand: edit the config and regenerate, otherwise the document and the "
        "warehouse will disagree and the document will be the one that is "
        "wrong."
    )
    lines.append("")
    lines.append(
        "Every measure below is implemented exactly once, in "
        "`mart_agency_month`, and the generator fails if a measure here is "
        "missing from that model or a measure in that model is missing here."
    )
    lines.append("")
    lines.append("## Parameters in force")
    lines.append("")
    lines.append("| Parameter | Value | Set in |")
    lines.append("| --- | --- | --- |")
    lines.append(f"| Ingest window start | `{cfg['ingest']['window_start']}` | `config/config.yml` |")
    lines.append(f"| SLA target | {cfg['sla']['default_target_days']} days | `config/config.yml` |")
    lines.append(f"| Maturity window | {cfg['maturity']['window_days']} days | `config/config.yml` |")
    lines.append(f"| Vintage cadence | {cfg['vintages']['cadence']} | `config/config.yml` |")
    lines.append("")

    lines.append("## Conventions that apply to every measure")
    lines.append("")
    for name, text in spec.get("conventions", {}).items():
        heading = name.replace("_", " ").capitalize()
        lines.append(f"**{heading}.** {' '.join(text.split())}")
        lines.append("")

    lines.append("## Measures")
    lines.append("")
    for metric in spec["metrics"]:
        lines.append(f"### {metric['label']}")
        lines.append("")
        lines.append(f"`{metric['name']}`")
        lines.append("")
        lines.append(f"**What it is.** {' '.join(metric['definition'].split())}")
        lines.append("")
        lines.append(f"**Grain.** {metric['grain']}")
        lines.append("")
        lines.append(f"**Numerator.** {' '.join(str(metric['numerator']).split())}")
        lines.append("")
        lines.append(f"**Denominator.** {' '.join(str(metric['denominator']).split())}")
        lines.append("")
        lines.append(f"**Filters.** {' '.join(str(metric['filters']).split())}")
        lines.append("")
        lines.append(f"**Caveats.** {' '.join(metric['caveats'].split())}")
        lines.append("")

    return "\n".join(lines) + "\n"


def check_against_mart(cfg, metric_names: set[str]) -> int:
    db_path = cfg.path("warehouse_db")
    if not db_path.exists():
        print(f"warehouse not built at {db_path}, skipping the implementation check")
        return 0

    con = duckdb.connect(str(db_path), read_only=True)
    try:
        cols = {
            r[0]
            for r in con.execute(
                """
                select column_name
                from information_schema.columns
                where lower(table_name) = 'mart_agency_month'
                """
            ).fetchall()
        }
    finally:
        con.close()

    if not cols:
        print("mart_agency_month not found, skipping the implementation check")
        return 0

    measure_cols = cols - NON_METRIC_COLUMNS
    documented_not_built = metric_names - cols
    built_not_documented = measure_cols - metric_names

    status = 0
    if documented_not_built:
        print(f"defined in metrics.yml but not implemented in mart_agency_month: {sorted(documented_not_built)}")
        status = 1
    if built_not_documented:
        print(f"implemented in mart_agency_month but not defined in metrics.yml: {sorted(built_not_documented)}")
        status = 1
    if status == 0:
        print(f"all {len(metric_names)} measures are defined and implemented, no drift")
    return status


def main() -> int:
    cfg = load_config()
    spec = load_metrics(cfg.repo_root)
    metric_names = {m["name"] for m in spec["metrics"]}

    out_path = cfg.repo_root / "reports" / "measure_dictionary.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(spec, cfg))
    print(f"wrote {out_path}")

    return check_against_mart(cfg, metric_names)


if __name__ == "__main__":
    raise SystemExit(main())
